language: python

python:
  - 3.6

bundler_args: --retry 3

install:
  - sudo apt-get update
  - sudo apt-get install texlive texlive-science texlive-latex-extra texlive-bibtex-extra texlive-fonts-extra
  - sudo apt-get install pdftk
  - ./scripts/travis_miniconda.sh
  - PATH="$HOME/miniconda/bin:$PATH"
  - conda env create -f environment.yml
  - source activate nlsy_dataset
script:
  - texhash
  - travis_wait python scripts/create_data.py
  - travis_wait python scripts/create_material.py
  - travis_wait python scripts/create_slides.py