language: python

python:
  - 3.6

bundler_args: --retry 3

install:
  - sudo apt-get update
  - sudo apt-get install texlive texlive-science texlive-latex-extra texlive-bibtex-extra texlive-fonts-extra
  - sudo apt-get install pdftk
  - pip install matplotlib
  - pip install numpy
  - pip install scipy
  - pip install statsmodels
  - pip install seaborn
script:
  - texhash
  - travis_wait python scripts/create_data.py
  - travis_wait python scripts/create_material.py
  - travis_wait python scripts/create_slides.py